[mypy]
plugins = sqlalchemy.ext.mypy.plugin
ignore_missing_imports = True
no_implicit_optional = False

[mypy.plugins.sqlalchemy]
include_type_annotations = False

[mypy-backend.services.landing.*]
disable_error_code = attr-defined

[mypy-backend.services.landing.templates]
disable_error_code = attr-defined

[mypy-backend.routes.*]
disable_error_code = arg-type,call-arg,attr-defined,index

[mypy-backend.services.webhook.*]
disable_error_code = union-attr,arg-type,assignment,operator

[mypy-backend.services.publications.*]
disable_error_code = union-attr,arg-type,var-annotated,index,assignment

[mypy-backend.services.channel.*]
disable_error_code = arg-type,assignment,union-attr,var-annotated,return-value,attr-defined,return

[mypy-backend.services.bot.*]
disable_error_code = arg-type,union-attr,assignment,return-value,operator,attr-defined

[mypy-backend.services.auth.*]
disable_error_code = assignment,return-value

[mypy-backend.services.storage]
disable_error_code = attr-defined

[mypy-backend.tasks.*]
disable_error_code = call-arg,operator
