"""Add media thumbnail urls

Revision ID: 018_add_media_thumbnail_urls
Revises: 017_add_text_templates
Create Date: 2026-01-15 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '018_add_media_thumbnail_urls'
down_revision: Union[str, None] = '017_add_text_templates'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('media_thumbnail_urls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'media_thumbnail_urls')
    # ### end Alembic commands ###
